=== StatCan/tass-ssat/tass-core/src/tass/core/schemas/tass_1.2.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "title": "TASS Execution File",
    "description": "A TASS job file, to be executed using the TASS framework.",
    "type": "object",
    "properties": {
        "schema-version": {
            "type": "string",
            "pattern": "^1\\.2(\\.(\\*|\\d+))?$"
        },
        "Job": {
            "description": "Description of the job. Sets default values for undefined test case values.",
            "type": "object",
            "properties": {
                "title": {
                    "description": "Name of the job. Defaults to the file name.",
                    "type": "string"
                },
                "uuid": {"$ref": "#/$defs/uuid"},
                "build": {
                    "description": "Build of the application being tested. Inherited by test cases if not specified.",
                    "type": "string"
                },
                "parent": {
                    "description": "Description of the parent job if generated from converter.",
                    "type": ["object", "string"],
                    "properties": {
                        "uuid": {"$ref": "#/$defs/uuid"},
                        "title": {
                            "description": "Title of the parent document.",
                            "type": "string"
                        },
                        "path": {
                            "description": "File path of the parent document at the time of conversion.",
                            "type": "string"
                        }
                    }
                },
                "hooks":{
                    "$ref": "#/$defs/uuid-list"
                }
            }
        },
        "Tests": {
            "description": "List of Test cases with configurations that may be executed.",
            "type": "array",
            "items": {"$ref": "#/$defs/test"}
        },
        "Cases": {
            "description": "List of Test cases that may be executed.",
            "type": "array",
            "items": {"$ref": "#/$defs/case"}
        },
        "Steps": {
            "description": "List of steps, singular actions, that can be executed in a test case.",
            "type": "array",
            "items": {"$ref": "#/$defs/step"}
        },
        "Browsers": {
            "description": "Browser configurations to be used in this test run.",
            "type": "array",
            "items": {"$ref": "#/$defs/browser"}
        },
        "Mobiles": {
            "description": "Mobile configurations to be used in this test run.",
            "type": "array",
            "items": {"$ref": "#/$defs/mobile"}
        },
        "Hooks": {
            "description": "Hook configurations for this test run.",
            "type": "array",
            "items": {"$ref": "#/$defs/hook"}
        },
        "Meta": {
            "description": "Additional information about this test run that does not affect the test.",
            "type": "object",
            "properties": {
                "results-path": {
                    "type": "string",
                    "description": "File path to write results. Overwrites default."
                },
                "pages-path": {
                    "type": "string",
                    "description": "File path to read POM files from."
                }
            }
        }
    },
    "$defs": {
        "uuid": {
            "type": "string",
            "description": "Universally Unique Identifier",
            "$comment": "Created as a definition for possible future functionality. Validating uuids."
        },
        "uuid-list": {
            "type": "array",
            "items": {
                "$ref": "#/$defs/uuid"
            },
            "description": "List of uuids"
        },
        "test": {
            "type": "object",
            "description": "Test to be executed. Includes which case and any other configuration settings.",
            "properties": {
                "uuid": {
                    "$ref": "#/$defs/uuid",
                    "description": "The uuid of this test. Typically a compounded uuid of the job, case, and configuration uuids."
                },
                "case": {
                    "$ref": "#/$defs/uuid",
                    "description": "The uuid of the case that will be executed."
                },
                "configuration": {
                    "type": "object",
                    "description": "Contains the various configurations for running a case.",
                    "properties": {
                        "browser": {
                            "$ref": "#/$defs/uuid",
                            "description": "The uuid of the browser used in this configuration."
                        },
                        "hooks": {
                            "$ref": "#/$defs/uuid-list"
                        }
                    }
                }
            }
        },
        "case": {
            "type": "object",
            "description": "Describes a singular test case. Test cases should be independant of one another.",
            "properties": {
                "uuid": {"$ref": "#/$defs/uuid"},
                "title": {
                    "type": "string",
                    "description": "Human readable descriptor for the test case."
                },
                "build": {
                    "type": "string",
                    "description": "Version of the application being tested."
                },
                "steps": {"$ref": "#/$defs/uuid-list"}
            },
            "required": ["uuid", "title", "steps"]
        },
        "step": {
            "type": "object",
            "description": "Describes a singular step, a single action to be takenby the automation.",
            "properties": {
                "uuid": {"$ref": "#/$defs/uuid"},
                "title": {
                    "type": "string",
                    "description": "Human readable descriptor for the step."
                },
                "action": {
                    "$comment": "TODO: Create external step schema to further validate steps for each action/parameters.",
                    "type": "array",
                    "minItems": 2,
                    "maxItems": 2,
                    "items":{
                        "type": "string"
                    },
                    "description": "An array with a length of 2, the first string states the module, the second the action."
                },
                "parameters": {
                    "type": "object",
                    "description": "Parameters content is dependant on the action used."
                }
            },
            "required": ["uuid", "title", "action", "parameters"]
        },
        "browser": {
            "type": "object",
            "description": "Configuration for a browser.",
            "properties": {
                "uuid": {"$ref": "#/$defs/uuid"},
                "browser_name": {
                    "enum": ["chrome", "firefox", "edge", "safari"],
                    "description": "The name of the browser to be used."
                },
                "configs": {
                    "type": "object",
                    "properties": {
                        "driver": {
                            "type": "object",
                            "description": "Configuration values for the automated driver."
                        },
                        "browser": {
                            "type": "object",
                            "description": "Configurations for browser preferences.",
                            "properties": {
                                "arguments": {
                                    "type": "array",
                                    "items": { "type": "string" },
                                    "description": "Flags to be passed to the browser instance"
                                },
                                "preferences": {
                                    "type": "object",
                                    "description": "Key value pairs to set preferences of a browser."
                                }
                            }
                        }
                    }
                }
            },
            "oneOf": [
                {"required": ["uuid", "browser_name", "configs"]},
                {"required": ["uuid", "driver_name", "configs"]}
            ]
        },
        "mobile": {
            "type": "object",
            "description": "Configuration for a mobile.",
            "properties": {
                "uuid": {"$ref": "#/$defs/uuid"},
                "driver_name": {
                    "enum": ["android", "ios"],
                    "description": "The name of the mobile platform to be used."
                },
                "configs": {
                    "type": "object",
                    "properties": {
                        "driver": {
                            "type": "object",
                            "description": "Configuration values for the automated driver."
                        },
                        "browser": {
                            "type": "object",
                            "description": "Configurations for browser preferences.",
                            "properties": {
                                "arguments": {
                                    "type": "array",
                                    "items": { "type": "string" },
                                    "description": "Flags to be passed to the browser instance"
                                },
                                "preferences": {
                                    "type": "object",
                                    "description": "Key value pairs to set preferences of a browser."
                                }
                            }
                        },
                        "appium:server": {
                            "type": "object",
                            "description": "Configurations for appium server/driver"
                        },
                        "appium:driver": {
                            "type": "object",
                            "description": "Capabilities for the appium driver."
                        }

                    },
                    "required": ["appium:driver", "appium:server"]
                }
            },
            "required": ["uuid", "driver_name", "configs"]
        },
        "hook":{
            "type": "object",
            "description": "A hook configuration",
            "properties": {
                "when": {
                    "type": "string",
                    "description": "String representation of the hook triggering event.",
                    "enum": ["before_run", "before_test", "on_start", "on_failure", "on_success", "on_finish", "after_test", "after_run"]
                },
                "hook": {
                    "type": "string",
                    "description": "The name of the hook."
                },
                "namespace": {
                    "type": "string",
                    "description": "The namespace the hook belongs to. EX: 'core', 'selenium'"
                },
                "critical": {
                    "type": "boolean",
                    "description": "Overwrites default hook failure severity."
                },
                "order": {
                    "type": "integer",
                    "description": "Number to define order of execution. Smaller values are executed first."
                },
                "args": {
                    "type": "object",
                    "description": "JSON object representing keyword arguments passed to the hook prior to execution."
                }
            },
            "required": ["when", "hook", "namespace"]
        }
    }
}

=== StatCan/tass-ssat/examples/demo/simple_demo_v2.json
{
    "schema-version": "1.2.0",
    "Job":
    {
        "uuid": "tr100101",
        "build": "V2.4",
        "title": "Simple Demo v.1",
        "parent": "None",
        "hooks": ["screenshot1", "screenshot2", "screenshot3", "screenshot4"]
    },
    "Hooks": [
        {
            "uuid": "screenshot1",
            "when": "on_failure",
            "hook": "screenshot",
            "namespace": "selenium"
        },
        {
            "uuid": "screenshot2",
            "when": "on_success",
            "hook": "screenshot",
            "namespace": "selenium"
        },
        {
            "uuid": "screenshot3",
            "when": "on_finish",
            "hook": "screenshot",
            "namespace": "selenium"
        },
        {
            "uuid": "screenshot4",
            "when": "on_start",
            "hook": "screenshot",
            "namespace": "selenium"
        }
    ],
    "Tests": [
        {
            "uuid": "tr100101--uuid-tc-01--chrome001",
            "case": "uuid-tc-01",
            "configurations": [
                {
                    "type": "browser",
                    "uuid": "chrome001"
                }
            ]
        },
        {
            "uuid": "tr100101--uuid-tc-01A--chrome001",
            "case": "uuid-tc-01A",
            "configurations": [
                {
                    "type": "browser",
                    "uuid": "chrome001"
                }
            ]
        },
        {
            "uuid": "tr100101--Uuid-tc-02--ffox002",
            "case": "Uuid-tc-02",
            "configurations": [
                {
                    "type": "browser",
                    "uuid": "ffox002"
                }
            ]
        },
        {
            "uuid": "tr100101--uuid-tc-01--ffox002",
            "case": "uuid-tc-01",
            "configurations": [
                {
                    "type": "browser",
                    "uuid": "ffox002"
                }
            ]
        }
    ],
    "Cases":
    [
        {
            "uuid": "uuid-tc-01",
            "title": "Tass Sample Case A - Fail",
            "steps": [
                "q1",
                "q1wait",
                "q2",
                "q3",
                "q4",
                "q5",
                "q6",
                "q7",
                "q8"
            ]
        },
        {
            "uuid": "uuid-tc-01A",
            "title": "Tass Sample Case A - Success",
            "steps": [
                "q1",
                "q1wait",
                "q2",
                "q3",
                "q4",
                "q5"
            ]
        },
        {
            "uuid": "Uuid-tc-02",
            "title": "Tass Sample Case B - Success",
            "steps": [
                "q1",
                "q2",
                "q3",
                "q4",
                "q5",
                "q1",
                "q2",
                "q3",
                "q4",
                "q5",
                "q6a"
            ]
        }
    ],
    "Steps": [
        {
            "uuid": "q1",
            "title": "Launch test page",
            "action": [
                "selenium",
                "load_file"
            ],
            "parameters": {
                "relative_path": "examples/demo-html/page1.html"
            }
        },
        {
            "uuid": "q1wait",
            "title": "test wait",
            "action": [
                "core",
                "wait"
            ],
            "parameters": {
                "wait_time": 5
            }
        },
        {
            "uuid": "q2",
            "title": "Assert page is open",
            "action": [
                "selenium",
                "assert_page_is_open"
            ],
            "parameters": {
                "page": [
                    "sample",
                    "page1"
                ]
            }
        },
        {
            "uuid": "q3",
            "title": "Wait for element then type",
            "action": [
                "selwait",
                "wait_element_visible"
            ],
            "parameters": {
                "locator": {
                    "by": "id",
                    "value": "nameField"
                },
                "action": [
                    "selenium",
                    "write"
                ],
                "text": "do a barrel roll"
            }
        },
        {
            "uuid": "q4",
            "title": "Click a button",
            "action": [
                "selenium",
                "click"
            ],
            "parameters": {
                "locator": "btnColor",
                "find": "wait_element_visible",
                "page": [
                    "sample",
                    "page1"
                ]
            }
        },
        {
            "uuid": "q5",
            "title": "Read CSS",
            "action": [
                "selenium",
                "read_css"
            ],
            "parameters": {
                "locator": "btnColor",
                "page": [
                    "sample",
                    "page1"
                ],
                "attribute": "background-color"
            }
        },
        {
            "uuid": "q6",
            "title": "Assert element is displayed",
            "action": [
                "selenium",
                "assert_displayed"
            ],
            "parameters": {
                "locator": "btnX",
                "page": [
                    "sample",
                    "page1"
                ],
                "soft": "true"
            }
        },
        {
            "uuid": "q7",
            "title": "Assert element is displayed",
            "action": [
                "selenium",
                "assert_displayed"
            ],
            "parameters": {
                "locator": "btnX",
                "page": [
                    "sample",
                    "page1"
                ]
            }
        },
        {
            "uuid": "q8",
            "title": "Assert element is displayed",
            "action": [
                "selenium",
                "assert_displayed"
            ],
            "parameters": {
                "locator": "btnX",
                "page": [
                    "sample",
                    "page1"
                ],
                "soft": "true"
            }
        },
        {
            "uuid": "q6a",
            "title": "Click a button",
            "action": [
                "selenium",
                "click"
            ],
            "parameters": {
                "locator": "btnFormat",
                "page": [
                    "sample",
                    "page1"
                ],
                "locator_args": [
                    "Color"
                ]
            }
        }
    ],
    "Browsers": [
        {
            "browser_name": "chrome",
            "uuid": "chrome001",
            "configs": {
                "driver": {
                    "implicit_wait": "5",
                    "explicit_wait": "10"
                },
                "browser": {
                    "arguments": [
                        "--start-maximized"
                    ],
                    "preferences": {}
                }
            }
        },
		{
            "browser_name": "chrome",
            "uuid": "chrome001A",
            "configs": {
                "driver": {
                    "implicit_wait": "5",
                    "explicit_wait": "10"
                },
                "browser": {
                    "arguments": [
                        "--window-size=1920,1080"
                    ],
                    "preferences": {}
                }
            }
        },
		{
            "browser_name": "chrome",
            "uuid": "chrome001B",
            "configs": {
                "driver": {
                    "implicit_wait": "5",
                    "explicit_wait": "10"
                },
                "browser": {
                    "arguments": [
                        "--window-size=900,600"
                    ],
                    "preferences": {}
                }
            }
        },
        {
            "browser_name": "chrome",
            "uuid": "chrome002",
            "configs": {
                "driver": {
                    "implicit_wait": "5",
                    "explicit_wait": "10"
                },
                "browser": {
                    "arguments": [
                        "--headless",
                        "--start-maximized"
                    ],
                    "preferences": {}
                }
            }
        },
        {
            "browser_name": "firefox",
            "uuid": "ffox001",
            "configs": {
                "driver": {
                    "implicit_wait": "15",
                    "explicit_wait": "30"
                },
                "browser": {
                    "arguments": [
                        "--start-maximized"
                    ],
                    "preferences": {}
                }
            }
        },
        {
            "browser_name": "firefox",
            "uuid": "ffox002",
            "configs": {
                "driver": {
                    "implicit_wait": "15",
                    "explicit_wait": "30"
                },
                "browser": {
                    "arguments": ["--headless"],
                    "preferences": {}
                }
            }
        }
    ]
}
